# Generated by Django 4.2.7 on 2024-09-21 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Views',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('display_image', models.FileField(upload_to='images/', verbose_name='Display Image')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('guest_capacity', models.IntegerField(verbose_name='Guest Capacity')),
                ('bedrooms', models.IntegerField(verbose_name='Bedrooms')),
                ('beds', models.IntegerField(verbose_name='Beds')),
                ('bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Has Wifi')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Has TV')),
                ('is_available', models.BooleanField(default=False, verbose_name='Is Available')),
                ('is_self_check_in', models.BooleanField(default=False, verbose_name='Is Self Check In')),
                ('is_pet_friendly', models.BooleanField(default=False, verbose_name='Is Pet Friendly')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csc.city', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
                'db_table': 'staywise_place',
                'managed': True,
            },
        ),
    ]
